[package]
name = "clrigctl"
version = "0.1.0"
edition = "2021"
author = "Martin Brodbeck <info@rustysoft.de>"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
