[package]
name = "clrigctl"
version = "0.1.0"
edition = "2021"
author = "Martin Brodbeck <info@rustysoft.de>"

[dependencies]
config = { version = "0.13.4", features = ["yaml"] }
home = "0.5.5"
reqwest = { version = "0.11.22", features = ["json","rustls"] }
serde = { version = "1.0.193", features = ["serde_derive"] }
serde_derive = "1.0.193"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }

