# This is an example config file. Please edit it to your needs
# and place it, for example, in your `$HOME/.config/`

power = "5" # Output power in W 

[cloudlog]
# Note: URL should end with "/index.php/api/radio".
url = "https://cloudlog.example.com/index.php/api/radio"
key = "clxxxxxxxxxxxxx"
identifier = "clrigctl"

[flrig]
# Note: Do not forget the "http://".
host = "http://127.0.0.1"
port = "12345"
