# This is an example config file. Please edit it to your needs
# and place it, for example, in your `$HOME/.config/wlrigctl/config.toml`

# Used to push data from flrig towards wavelog
[wavelog]
# Note: URL should end with "/index.php/api/radio".
url = "http://localhost/index.php/api/radio"
qso_url = "http://localhost/api/qso"
key = "wlxxxxxxxxxxxxx"
identifier = "my-radio-model"

# This is an index used by wavelog to discriminate between multiple station
# descriptions. Most users will need 1 here.
station_profile_id = 1
# interval is in milliseconds
interval = 1000



# Used to retrieve data from the radio, to supply live VFO freq to QSO window
[flrig]
# Note: Do not forget the "http://".
host = "http://127.0.0.1"
port = 12345

# In Watts; needed to scale 0-100 from FLRig into Watts for Wavelog QSO
# It would be nice if we could reliably query all radios for max. power, but...
maxpower = "10"

# on IC-703, set_bandwidth() with index 1 selects narrow 250Hz filter for CW
# (if fitted...)
cwbandwidth = 1



# This is the reverse direction from wavelog, when a user clicks a callsign on
# the bandmap and we want to qsy to that frequency.
[CAT]
host = "127.0.0.1"
port = 54321

# boolean flag to select use of Yaesu explicit -U or -L modes when mapping from
# wavelog to flrig.
# e.g. "CW-U" instead of "CW"
yaesu = false


# For capturing QSO ADIF from WSJT-X
[WSJTX]
host = "127.0.0.1"
port = 2237

# error timeout in seconds
err_timeout = 3
